config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    get 'signup', to: 'devise/registrations#new'
    # signup の post もやるべきかな
    delete 'logout', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do

    # postのそれぞれに対して、commentsをつける
    resources :comments, only: [:create]
    
    # memberは特定のデータに対して
    member do
      post 'status_update'
    end

    # collectionは全てのデータに対して
    collection do
      get 'search'
    end
    
  end

  # resources :posts do
  #   member do
  #     post 'status_update'
  #   end
  # end

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  # user
  belongs_to :provider,  class_name: 'User'                #, foreign_key: 'provider'
  belongs_to :recipient, class_name: 'User', optional: true#, foreign_key: 'recipient'
  # belongs_to :provider_id,  class_name: 'User'                #, foreign_key: 'provider'
  # belongs_to :recipient_id, class_name: 'User', optional: true#, foreign_key: 'recipient'

  # validates
  validates :provider, presence: true
  validates :title,    presence: true, length: { minimum: 1 , maximum: 30}
  validates :lecture,  presence: true, length: { minimum: 1 , maximum: 20}
  validates :status,   presence: true
  validates :content,  presence: true, length: { minimum: 1 , maximum: 100}
  validates :condition,presence: true

  #image
  mount_uploader :image, ImageUploader

  # comments
  has_many :comments

  enum status: {
    募集中: 0, 募集終了: 1
  }
  enum condition:{
    新品同様: 1, 書き込みがある: 2, 汚れが目立つ: 3, きたない: 4
  }

   # Postを特定するための検索。Adminで使う予定
   def self.search(title, lecture, status)
    if title
      @posts = where('(title LIKE ? )', "%#{title}%")
      @posts.where('(lecture LIKE ? )', "%#{lecture}%") if lecture
    elsif lecture
      @posts.where('(lecture LIKE ? )', "%#{lecture}%")
    else
      @posts = self.all
    end
    # @posts.where(status: status)
  end

  # Postを特定するためではなく、なるべく多く拾ってくる検索
  def self.search_slack(key_words)
    if key_words
      # 1byteのスペースと2byteのスペースで文字を分割
      @posts = where(status: "存在しない") #とりあえず@postsを作成する
      key_words.split(/[ |　]/).each_with_index do |char, i|
        continue if char == (" " or "　") # 検索のキーワードの最初と最後に空白が入ることがあったので、それをスルー
        @posts += where('(title LIKE ? )', "%#{char}%").where(status: "募集中") 
        @posts += where('(lecture LIKE ? )', "%#{char}%").where(status: "募集中") 
      end
      return @posts
    else
      @posts = self.all
    end
    # @posts.where(status: status)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
          
  # posts
  has_many :provider_posts, class_name: 'Post', dependent: :destroy
            #, foreign_key: 'provider',
  has_many :recipient_posts, class_name: 'Post'
            #, foreign_key: 'recipient'

  # comments
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            added_attrs = [ :email, :username, :password, :password_confirmation ]
            devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
            devise_parameter_sanitizer.permit :account_update, keys: added_attrs
            devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
          end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new(comment_params)
        @comment.user_id = current_user.id
        redirect_back(fallback_locatuin: root_path) unless user_signed_in?
        if @comment.save!
            redirect_back(fallback_location: root_path)
        else
            redirect_to("/") and return
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:content, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :status_update, :destroy]

  def index
    @post  = Post.new
    @posts = Post.all
  end

  def show
    @post  = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def search
    # @posts = Post.search(params[:title],params[:lecture],params[:status])

    #ゆるい方の検索
    @posts = Post.search_slack(params[:key_words])
  end

  def status_update
    @post  = Post.find(params[:id])
    @post.recipient = current_user
    if @post.update(post_status)
      OfferMailer.offer_email(@post.provider, @post.recipient, @post).deliver
      redirect_to(post_path(@post.id))
    else
      redirect_to(post_path(@post.id))
    end
  end

  def create
    @post = Post.new(post_params)
    @post.provider = current_user
    if @post.save
      flash.now[:notice] = '保存しました。'
      # redirect_back(fallback_location: root_path)
      redirect_to(post_path(@post.id))
    else
      @posts = Post.all
      flash.now[:alert] = '保存に失敗しました。入力が正しくありません。'
      render :index, posts: @posts
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    # 本人じゃなかったらルートパスにふぁっきん送り返す
    if not(authenticate_identity(@post))
      redirect_back(fallback_location: root_path) and return
    end

    if @post.update(post_params)
      redirect_to(post_path(@post.id))
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    # @postのproviderではない場合、削除させないようにする
    if not(authenticate_identity(@post))
      redirect_back(fallback_location: root_path) and return
    end

    if @post.destroy!
      redirect_to('/') and return
    else
      redirect_to('/') and return
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :lecture, :content, :condition, :image, :image_cache, :remove_image)
    end

    def post_status
      params.require(:post).permit(:status)
    end

    # postへの変更を本人しか行えないようにする
    def authenticate_identity(post)
      post.provider == current_user ? true : false
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(provider: @user)

    # ユーザー詳細ページで表示するpostを取得。取得時にstatusごとにわけとかないといい感じに表示できなかった
    @posts_bosyu     = Post.where(provider: @user).where(status: "募集中")
    @posts_delivered = Post.where(provider: @user).where(status: "募集終了")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%br/
%br/
%br/
%footer.page-footer.font-small.unique-color-dark.pt-4.bg-secondary.border-top.border-dark
  .container
    %ul.list-unstyled.list-inline.text-center
      %li.list-inline-item
        %a.btn-floating.btn-fb.mx-1
          %p aaa
      %li.list-inline-item
        %a.btn-floating.btn-tw.mx-1
          %p bbb
  .footer-copyright.text-center.py-3
    © 2019 Copyright:俺

app/views/layouts/_header.html.haml
/
  粗探ししないでください。
%nav#mainNav.navbar.navbar-dark.bg-dark.fixed-top
  = link_to "Yuzuru-OSU", root_path, class: "navbar-brand"
  #navbarResponsive.navbar-nav-scroll
    %ul.navbar-nav.ml-auto.flex-row
      %li.nav-item.mx-0.mx-lg-1
        = link_to "教材を探す", search_posts_path, class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
      - if user_signed_in?
        %li.nav-item.mx-0.mx-lg-1
          = link_to "#{current_user.username} プロフィール", user_path(current_user.id), class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
        %li.nav-item.mx-0.mx-lg-1
          = link_to "logout", logout_path, method: :delete, class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
      - else
        %li.nav-item.mx-0.mx-lg-1
          = link_to "SignUp", signup_path, class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
        %li.nav-item.mx-0.mx-lg-1
          = link_to "LogIn", login_path, class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"

app/views/layouts/_notification.html.haml
.notifications
  - flash.each do |name, msg|
    = content_tag :div, msg, class: name

app/views/layouts/_posting.html.haml
.jumbotron.jumbotron-fluid.text-bslack.rounded.bg-light
  .container
    %br/
    = render 'layouts/notification'
    - if user_signed_in?
      %h3.display-4.font-italic Post your TEXT
      .panel.panel-default
        .panel-body
          = form_for @post do |f|
            .form-group.row
              = f.label :タイトル , class: "col-sm-2 col-form-label"
              .col-sm-10
                = f.text_field :title, placeholder: "書名を入力",autofocus: true,class: "form-control"
            .form-group.row
              = f.label :講義名 , class: "col-sm-2 col-form-label"
              .col-sm-10
                = f.text_field :lecture, placeholder: "講義名を入力", class: "form-control"
            .form-group.row
              = f.label :コンディション , class: "col-sm-2 col-form-label"
              .col-sm-10
                = f.select :condition,  [["新品同様", "新品同様"],  ["書き込みがある", "書き込みがある"], ["汚れが目立つ", "汚れが目立つ"],["きたない", "きたない"] ], |
                  { include_blank: "- 状態を選択 -", selected: "- 状態を選択 -" }                                                      |
            .form-group.row
              = f.label :説明, class: "col-sm-2 col-form-label"
              .col-sm-10
                = f.text_area :content, placeholder: "多少の書き込みはあるけど、全然使えます！など、少しでも入力してください。", class: "form-control"
            .form-group.row
              = f.label :画像, class: "col-sm-2 col-form-label"
              .col-sm-10
                = image_tag @post.image.thumb100.url if @post.image?
                = f.file_field :image, class: "btn btn-block"
                = f.hidden_field :image_cache
            .form-group.row
              .col-sm-4
              .col-sm-4
                = f.submit '投稿' , class: "btn btn-block btn-outline-dark"
              .col-sm-4
    - else
      .container.row
        %h2.display-4.font-italic about Yuzuru
        %p.lead.my-3
          Yuzuru-OSUは、人から人へ教科書を「ゆずる」手助けをするサービスです。
          %br/
          大阪産業大学の学生を対象にしていて、あなたが探している教材や参考書がきっと見つかると思います。
          %br/
          ぜひ、ユーザー登録して、譲ったり譲られたり...色々体験してみてください。
        .col-sm-4
        .col-sm-4
          = link_to 'ユーザー登録' , signup_path, class: "btn btn-block btn-outline-dark"
        .col-sm-4

app/views/layouts/_search.html.haml
= form_tag search_posts_path, method: :get do
  = label_tag :タイトル
  = text_field_tag :title, params[:title]
  = label_tag :講義名
  = text_field_tag :lecture, params[:lecture]
  /
    <haml_loud> select_tag params[:status], options_for_select([[&quot;掲載中&quot;,&quot;掲載中&quot;],[&quot;受け渡し中&quot;,&quot;受け渡し中&quot;],[&quot;受け渡し完了&quot;,&quot;受け渡し完了&quot;]], selected: 0) </haml_loud>
  %br/
  = submit_tag "検索", class: "btn btn-block btn-outline-dark"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title YuzuruOsu
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/edit.html.haml
%h1 投稿編集
= form_for @post do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :lecture
    = f.text_field :lecture
  %p
    = f.label :condition
    = f.select :condition, [["新品同様", "新品同様"], ["書き込みがある", "書き込みがある"],  ["汚れが目立つ", "汚れが目立つ"], |
      ["きたない", "きたない"]],  :prompt => "選択してください", class: "form-control"                       |
  %p
    = f.label :content
    = f.text_area :content
  - if @post.image?
    %p 現在のイメージ
    = image_tag @post.image.thumb100.url
  %p
    = f.label :image
    = f.file_field :image
  %p
    = f.check_box :remove_image
    = f.label :remove_image, "画像を削除する"
  = f.submit "保存"
- if @post.provider == current_user
  %p= link_to '削除', post_path(@post.id), method: :delete
= link_to "ホームへ戻る", posts_path

app/views/posts/index.html.haml
= render 'layouts/header'
= render 'layouts/posting'
.container
  .row
    .col-md-4
    .col-md-4
      %br/
      %h2.text-center.font-weight-light Latest Texts
      %br/
    .col-md-4
  .row
    .col-md-4
    .col-md-4
      = form_tag search_posts_path, method: :get do
        .form-group.row
          .col-sm-9
            = text_field_tag :key_words, params[:key_words], placeholder: "書名や講義名を入力", class: "form-control"
          .col-sm-3
            = submit_tag '検索' , class: "btn btn-block btn-outline-dark"
      %br/
    .col-md-4
.container
  .row
    .col-md-1
    .col-md-10
      .container.row
        - @posts.reverse_each do |post|
          .col-2
            - if post.image?
              = image_tag post.image.thumb100.url
            - else
              .text-center
                = image_tag 'noimage_100.png'
          .col-4
            %table.table
              %thead
                %tr
                  %th{:colspan => "2"}
                    = link_to post.title, post_path(post.id), class: "font-weight-bold"
              %tbody
                %tr
                  %td 講義名
                  %td= post.lecture
                %tr
                  %td ステータス
                  %td= post.status
            %br/
    .col-md-1
= render 'layouts/footer'

app/views/posts/search.html.haml
= render 'layouts/header'
.jumbotron.jumbotron-fluid.text-bslack.rounded.bg-light
  .container
    %br/
    .row
      .col-2
      .col-8
        %h3.display-4.font-italic Search TextBook
      .col-2
    .panel.panel-default
      .panel-body
        = form_tag search_posts_path, method: :get do
          .form-group.row
            .col-sm-2
            .col-sm-8
              %p.col-form-label 教材の名前、講義名を入力してください。
              %p.col-form-label キーワードに関連する募集中の投稿のみを探します！
            .col-sm-2
          .form-group.row
            .col-sm-2
            .col-sm-6
              = text_field_tag :key_words, params[:key_words], placeholder: "書名 や 講義名", autofocus: true,class: "form-control"
            .col-sm-2
              = submit_tag '検索' , class: "btn btn-block btn-outline-dark"
            .col-sm-2
.container
  .row
    - @posts.each do |post|
      .col-md-2
        - if post.image?
          = image_tag post.image.thumb100.url
        - else
          .text-center
            = image_tag 'noimage_100.png'
      .col-4
        %table.table
          %thead
            %tr
              %th{:colspan => "2"}
                = link_to post.title, post_path(post.id), class: "font-weight-bold"
          %tbody
            %tr
              %td 講義名
              %td= post.lecture
        %br/
= render 'layouts/footer'

app/views/posts/show.html.haml
= render 'layouts/header'
%br/
%br/
%br/
%br/
%br/
.container
  .row
    .col-md-2
    .col-md-4
      - if @post.image?
        = image_tag @post.image.thumb300.url
      - else
        .text-center
          = image_tag 'noimage.png'
    .col-md-4
      %table.table
        %thead
          %tr
            %th{:colspan => "2"}
              = @post.title
        %tbody
          %tr
            %td 講義名
            %td= @post.lecture
          %tr
            %td ステータス
            %td= @post.status
          %tr
            %td 説明
            %td= @post.content
          %tr
            %td コンディション
            %td= @post.condition
          %tr
            %td 提供者
            %td= link_to @post.provider.username, user_path(@post.provider.id)
    .col-md-2
  - if @post.provider == current_user
    .row
      .col-md-4
      .col-md-4
        %br/
        %p.text-center
          = link_to '編集', edit_post_path(@post.id)
          = link_to '削除', post_path(@post.id), method: :delete
      .col-md-4
  %br/
  .row
    .col-md-4
    .col-md-4
      - if @post.recipient.nil?
        / @post.recipient is NULL
        - if user_signed_in?
          / @user signed in
          - if @post.provider == current_user
            / @user is PROVIDER
          - else
            / @user isn't PROVIDER
            = form_for @post, url: status_update_post_path(@post.id), method: :post do |f|
              = f.hidden_field :status, value: "受け渡し中"
              = f.submit 'オファーを送る', class: "btn btn-block btn-outline-primary"
        - else
          / user don't signed in
          = form_for @post, url: status_update_post_path(@post.id), method: :post do |f|
            = f.hidden_field :status, value: "受け渡し中"
            = f.submit 'オファーを送る', class: "btn btn-block btn-outline-primary"
      - else
        / @post.recipient is not NULL
        %button.btn.btn-block.btn-warning{:disabled => "disabled"} 募集終了
    .col-md-4
  %hr/
  %br/
  .row
    .col-md-2
    .col-md-2
      %h4 コメント
    .col-md-4
      - if @comments.length == 0
        %p コメントはありません
      - else
        - @comments.each do |c|
          .form-group.row
            .col-sm-3
              = link_to c.user.username, user_path(c.user.id)
            .col-sm-9
              = c.content
    .col-md-4
  %br/
  %br/
  .row
    .col-md-2
    .col-md-2
      %h4 コメントする
    - if user_signed_in?
      .col-md-4
        = form_for [@post, @comment] do |f|
          .form-group.row
            .col-sm-12
              = f.text_field :content, class: "form-control"
          = f.hidden_field :post_id, value: @post.id
          .form-group.row
            .col-sm-12.text-center
              = f.submit '投稿', class: "btn btn-outline-dark"
    - else
      .col-md-4
        .text-center
          = link_to 'ログインしてコメントする', login_path, class: "btn btn-outline-dark"
    .col-md-4
%hr/
.text-center
  %br/
  = link_to "ホーム", posts_path
= render 'layouts/footer'

app/views/users/index.html.haml
%h1 ユーザー一覧
- @users.each do |user|
  %a{:href => "/users/#{user.id}"}= user.email
  %hr/
= link_to "ホームへ戻る", posts_path

app/views/users/show.html.haml
= render 'layouts/header'
%br/
%br/
%br/
.container
  .row
    .col-md-4
    .col-md-4
      %br/
      - if user_signed_in?
        - if @user.username == current_user.username
          %h2.text-center.font-weight-light My Profile
        - else
          %h2.text-center.font-weight-light
            = @user.username
            's Profile
      - elsif not(user_signed_in?)
        %h2.text-center.font-weight-light
          = @user.username
          's Profile
      %br/
    .col-md-4
.container
  .row
    .col-md-2
    .col-md-2
      %h4 基本情報
      - if user_signed_in?
        - if @user.id == current_user.id
          = link_to "Edit", edit_user_registration_path(current_user.id)
    .col-md-6
      %p
        ニックネーム: #{@user.username}
      %p
        総投稿数: #{@posts.length}
      %p
        登録日: #{@user.created_at.strftime('%Y年%m月%d日')}
      %hr/
    .col-md-2
  %br/
  %br/
  .row
    .col-md-2
    .col-md-2
      %h4.font-weight-light Users Posts
    .col-md-6
      /
        <haml_silent>       if @posts_bosyu
        </haml_silent><haml_block><haml_silent>         @posts_bosyu.each do |post|
        </haml_silent><haml_block>          <haml_loud> link_to post.title, post_path(post.id) </haml_loud>
        <hr>
        </haml_block></haml_block><haml_silent>       else
        </haml_silent><haml_block>        <h4>募集中の投稿がありません。</p>
        </haml_block>
      %table.table
        %thead
          %tr
            %th Bosyu now
        %tbody
          - if @posts_bosyu.length > 0
            - @posts_bosyu.each do |post|
              %tr
                %td= link_to post.title, post_path(post.id)
          - else
            %tr
              %td 募集中の投稿がありません
        %thead
          %tr
            %th Delivered Posts
        %tbody
          - if @posts_delivered.length > 0
            - @posts_delivered.each do |post|
              %tr
                %td= link_to post.title, post_path(post.id)
          - else
            %tr
              %td 譲った教材はありません
    .col-md-2
= render 'layouts/footer'